//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2016 Retargetable Decompiler <info@retdec.com>
//

#include <errno.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ----------------- Float Types Definitions ------------------

typedef float float32_t;
typedef double float64_t;
typedef long double float80_t;

// ------------------------ Structures ------------------------

struct struct__IO_FILE {
    int32_t e0;
    char * e1;
    char * e2;
    char * e3;
    char * e4;
    char * e5;
    char * e6;
    char * e7;
    char * e8;
    char * e9;
    char * e10;
    char * e11;
    struct struct__IO_marker * e12;
    struct struct__IO_FILE * e13;
    int32_t e14;
    int32_t e15;
    int32_t e16;
    int16_t e17;
    char e18;
    char e19[1];
    char * e20;
    int64_t e21;
    char * e22;
    char * e23;
    char * e24;
    char * e25;
    int32_t e26;
    int32_t e27;
    char e28[40];
};

struct struct__IO_marker {
    struct struct__IO_marker * e0;
    struct struct__IO_FILE * e1;
    int32_t e2;
};

// ------------------- Function Prototypes --------------------

int32_t ProceedTransaction(char ** a1, char * a2, struct struct__IO_FILE * a3, struct struct__IO_FILE * a4, char * a5, int32_t a6);

// --------------------- Global Variables ---------------------

int32_t g1 = 0; // esp

// ------------------------ Functions -------------------------

// Address range: 0x8048b04 - 0x804901c
int32_t ProceedTransaction(char ** a1, char * a2, struct struct__IO_FILE * a3, struct struct__IO_FILE * a4, char * a5, int32_t a6) {
    // 0x8048b04
    if ((float64_t)(int64_t)(int32_t)a5 <= 1.0e+4) {
        // if_8048b3f_0_false
        // branch -> after_if_8048b3f_0
    }
    // after_if_8048b3f_0
    int32_t result; // bp+150
    if ((float64_t)(int64_t)(int32_t)a5 < 0.0) {
        // after_if_8048b53_0
        result = -13;
        // branch -> 0x8049016
    } else {
        // if_8048b53_0_false
        if ((float64_t)(int64_t)(int32_t)a5 <= 0.0) {
            // if_8048b53_1_false
            // branch -> after_if_8048b53_0.thread
        }
        char * mem = malloc(0x2000); // 0x8048b6f
        sprintf(mem, "SELECT balance FROM accounts WHERE account_id = %s", a3);
        strlen(mem);
        strlen(mem);
        int32_t str = (int32_t)a1; // 0x8048bc2
        mysql_real_query();
        free(mem);
        if (str == 0) {
            // 0x8048beb
            mysql_store_result();
            if (str != 0) {
                // 0x8048c09
                mysql_fetch_row();
                strtod((char *)*(int32_t *)str, NULL);
                // branch -> 0x8049016
            }
            // 0x8049016
            return -22;
        }
        result = -22;
    }
    // 0x8049016
    return result;
}

// Address range: 0x804901d - 0x804a4af
int main(int argc, char ** argv) {
    float80_t v1 = 0.0; // st7
    int32_t v2 = (int32_t)argv; // 0x804901d_1
    int32_t v3 = v2;
    char ** v4;
    int32_t v5 = (int32_t)&v4; // 0x804902e_3
    g1 = v5;
    char ** str = (char **)&v3; // bp-500
    int32_t v6 = *(int32_t *)20; // 0x8049040
    if ((char *)argc > (char *)6) {
        int32_t size = -((-1 * strlen((char *)(v2 + 1)))); // 0x8049087
        v4 = (char **)size;
        char * mem = malloc(size); // 0x804908d
        v4 = (char **)mem;
        strcpy(mem, *str);
        int32_t size2 = -((-1 * strlen((char *)((int32_t)*str + 1)))); // 0x80490e2
        v4 = (char **)size2;
        char * mem2 = malloc(size2); // 0x80490e8
        v4 = (char **)mem2;
        strcpy(mem2, *str);
        int32_t size3 = 1 - -1 * strlen(*str); // 0x8049138
        v4 = (char **)size3;
        char * mem3 = malloc(size3); // 0x8049143
        v4 = (char **)mem3;
        strcpy(mem3, *str);
        int32_t size4 = -((-1 * strlen((char *)((int32_t)*str + 1)))); // 0x8049198
        v4 = (char **)size4;
        char * mem4 = malloc(size4); // 0x804919e
        v4 = (char **)mem4;
        strcpy(mem4, *str);
        int32_t size5 = 1 - -1 * strlen(*str); // 0x80491ee
        v4 = (char **)size5;
        char * mem5 = malloc(size5); // 0x80491f9
        v4 = (char **)mem5;
        strcpy(mem5, *str);
        int32_t size6 = 1 - -1 * strlen(*str); // 0x8049249
        v4 = (char **)size6;
        char * mem6 = malloc(size6); // 0x8049254
        v4 = (char **)mem6;
        strcpy(mem6, *str);
        v4 = (char **)mem;
        struct struct__IO_FILE * file = fopen(mem, "r"); // 0x804928e
        int32_t result; // bp+234
        if (file == NULL) {
            // 0x80492a2
            v4 = NULL;
            perror(NULL);
            result = 2;
            // branch -> 0x804a48c
        } else {
            // 0x80492b8
            v4 = (char **)file;
            fseek(file, 0, SEEK_END);
            v4 = (char **)file;
            int32_t curr_file_offset = ftell(file); // 0x80492df
            v4 = (char **)file;
            fseek(file, 0, SEEK_SET);
            int32_t size7 = curr_file_offset + 1; // 0x804930e
            char ** v7 = (char **)size7; // 0x8049311_0
            v4 = v7;
            char * mem7 = malloc(size7); // 0x8049314
            v4 = v7;
            char * mem8 = malloc(size7); // 0x804932b
            if (mem7 != NULL) {
                // 0x804933f
                if (mem8 != NULL) {
                    int32_t str6 = 0;
                    int32_t * v8;
                    *v8 = 0;
                    int32_t v9 = 4; // 0x8049387146
                    int32_t v10; // 0x80493aa
                    int32_t v11; // 0x8049db8
                    int32_t v12; // 0x8049e41
                    int32_t v13; // 0x8049dbf
                    int32_t v14; // 0x8049390_0
                    int32_t v15; // 0x80499e0_4
                    int32_t v16; // 0x8049d93_4
                    int32_t v17; // ecx
                    int32_t v18; // edx
                    int32_t str3;
                    int32_t v19;
                    int16_t str2;
                    int32_t v20;
                    int32_t v21;
                    int32_t v22; // 0x804902c64
                    int32_t v23; // 0x8049dc1
                    int32_t v24; // 0x8049dd7
                    unsigned char v25; // 0x8049e0b
                    int32_t v26;
                    int32_t v27;
                    int32_t v28; // 0x8049dd0
                    int32_t v29;
                    if (v9 < 28) {
                        v8[v9] = 0;
                        int32_t v30 = v9 + 4; // 0x8049387
                        while (v30 < 28) {
                            // 0x8049384
                            v8[v30] = 0;
                            v30 += 4;
                            // continue -> 0x8049384
                        }
                        // 0x80493a7
                        v14 = &str6;
                        str6 = 0;
                        *(int32_t *)(v14 + 4) = 0;
                        v10 = 8;
                        v26 = v14;
                        v29 = 0;
                        // branch -> 0x80493a7
                        while (v10 < 20) {
                            // 0x80493a7
                            *(int32_t *)(v26 + v10) = v29;
                            v10 += 4;
                            v26 = v14;
                            v29 = 0;
                            // continue -> 0x80493a7
                        }
                        // 0x80493b1
                        *(char *)(v10 + v26) = (char)v29;
                        v15 = &v19;
                        // branch -> 0x80493bb
                        char * next_token4; // 0x8049494
                        int16_t accept;
                        char accept2;
                        while (true) {
                            // 0x80493bb
                            v4 = (char **)mem7;
                            memset(mem7, 0, size7);
                            v4 = (char **)mem8;
                            memset(mem8, 0, size7);
                            v4 = (char **)mem7;
                            fgets(mem7, curr_file_offset, file);
                            v4 = (char **)mem7;
                            if (memcmp(mem7, mem8, curr_file_offset) == 0) {
                                // 0x8049dab
                                str3 = 0;
                                v17 = 0;
                                v16 = &v20;
                                v18 = 28;
                                int32_t v31 = 0; // 0x8049db5
                                int32_t v32 = v16; // 0x8049db5
                                v22 = 0;
                                // branch -> 0x8049db5
                                char ** v33; // 0x05993
                                while (true) {
                                    // 0x8049db5
                                    *(int32_t *)(v22 + v32) = v31;
                                    v11 = v22 + 4;
                                    v27 = v16;
                                    if (v11 >= 28) {
                                        // 0x8049dbf
                                        v13 = v27 + v11;
                                        v23 = v18;
                                        v24 = v13;
                                        v28 = v23;
                                        if ((v23 & 2) != 0) {
                                            // 0x8049dca
                                            *(int16_t *)v13 = (int16_t)v17;
                                            v24 = v13 + 2;
                                            v28 = v18;
                                            // branch -> 0x8049dd0
                                        }
                                        // 0x8049dd0
                                        if (v28 % 2 != 0) {
                                            // 0x8049dd7
                                            *(char *)v24 = (char)v17;
                                            // branch -> 0x8049ddc
                                        }
                                        // 0x8049ddc
                                        str2 = 0;
                                        v21 = 0;
                                        v25 = *(char *)(v21 + v14);
                                        sprintf((char *)&str2, "%02x", (int32_t)v25);
                                        strcat((char *)&str3, (char *)&str2);
                                        v12 = v21 + 1;
                                        // branch -> 0x8049e02
                                        while (v12 < 32) {
                                            // 0x8049e02
                                            v21 = v12;
                                            v25 = *(char *)(v21 + v14);
                                            sprintf((char *)&str2, "%02x", (int32_t)v25);
                                            strcat((char *)&str3, (char *)&str2);
                                            v12 = v21 + 1;
                                            // continue -> 0x8049e02
                                        }
                                        // 0x8049e51
                                        v4 = (char **)file;
                                        fseek(file, 0, SEEK_SET);
                                        if (strcmp((char *)&str3, mem6) == 0) {
                                            // 0x8049ea0
                                            // branch -> 0x8049ea0
                                          lab_0x8049ea0:;
                                            char * next_token; // 0x8049f79
                                            while (true) {
                                                // 0x8049ea0
                                                v4 = (char **)mem7;
                                                memset(mem7, 0, size7);
                                                v4 = (char **)mem8;
                                                memset(mem8, 0, size7);
                                                v4 = (char **)mem7;
                                                fgets(mem7, curr_file_offset, file);
                                                v4 = (char **)mem7;
                                                if (memcmp(mem7, mem8, curr_file_offset) != 0) {
                                                  lab_0x8049f40:
                                                    // 0x8049f40
                                                    v4 = (char **)mem8;
                                                    memcpy(mem8, mem7, size7);
                                                    v4 = (char **)mem7;
                                                    next_token = strtok(mem7, ",");
                                                    if (next_token != NULL) {
                                                        // break -> 0x8049f91
                                                        break;
                                                    }
                                                    // continue -> 0x8049ea0
                                                    continue;
                                                }
                                            }
                                            // 0x8049f91
                                            accept = 0x3130;
                                            int32_t * v34; // 0x04683
                                            char ** v35; // bp+058
                                            if (-((-1 * strlen(next_token))) == 34) {
                                                // 0x804a020
                                                v4 = (char **)next_token;
                                                if (strspn(next_token, (char *)&accept) == 34) {
                                                    int32_t size8 = 1 - -1 * strlen(next_token); // 0x804a07d
                                                    v4 = (char **)size8;
                                                    char * mem9 = malloc(size8); // 0x804a088
                                                    v4 = (char **)mem9;
                                                    strcpy(mem9, next_token);
                                                    v35 = (char **)mem9;
                                                    v34 = NULL;
                                                    // branch -> 0x804a0ab
                                                } else {
                                                    v35 = NULL;
                                                    v34 = (int32_t *)-35;
                                                }
                                            } else {
                                                // 0x804a0ab
                                                v35 = NULL;
                                                v34 = (int32_t *)-34;
                                                // branch -> 0x804a0ab
                                            }
                                            // 0x804a0ab
                                            v4 = NULL;
                                            char * next_token2 = strtok(NULL, ","); // 0x804a0bb
                                            int32_t * v36 = next_token2 == NULL ? (int32_t *)-31 : v34; // bp+045
                                            *__errno_location() = 0;
                                            float64_t str_as_d = 0.0; // 0x804a3ae36
                                            if (next_token2 != NULL) {
                                                // 0x804a0f5
                                                v4 = (char **)next_token2;
                                                str_as_d = strtod(next_token2, NULL);
                                                // branch -> 0x804a111
                                            }
                                            int32_t * v37 = v36; // bp+044
                                            char * next_token3; // 0x804a15b
                                            int32_t * v38; // bp+042
                                            int32_t * v39; // bp+043
                                            if (v36 == NULL) {
                                                // 0x804a11a
                                                if (str_as_d >= 0.0) {
                                                    // if_804a122_0_false
                                                    if (str_as_d <= 0.0) {
                                                        // if_804a122_1_false
                                                        if (str_as_d != 0.0) {
                                                          lab_0x804a136:
                                                            // 0x804a136
                                                            if (*__errno_location() == 0) {
                                                                v37 = NULL;
                                                              lab_0x804a14b:
                                                                // 0x804a14b
                                                                v4 = NULL;
                                                                next_token3 = strtok(NULL, ",");
                                                                v39 = next_token3 == NULL ? (int32_t *)-31 : v37;
                                                                v38 = v39;
                                                                if (v39 == NULL) {
                                                                  lab_0x804a182:
                                                                    // 0x804a182
                                                                    if (-((-1 * strlen(next_token3))) >= 151) {
                                                                        // 0x804a1b1
                                                                        v38 = (int32_t *)-37;
                                                                        // branch -> 0x804a1fa
                                                                    } else {
                                                                        v38 = NULL;
                                                                    }
                                                                }
                                                              lab_0x804a1fa:
                                                                // 0x804a1fa
                                                                accept2 = 48;
                                                                int32_t v40;
                                                                memcpy((char *)&v40, (char *)0x804a739, 16);
                                                                *(int16_t *)&v40 = *(int16_t *)0x804a739;
                                                                *(char *)((int32_t)&v40 | 2) = *(char *)0x804a73b;
                                                                int32_t * v41 = v38;
                                                                int32_t * v42; // bp+038
                                                                if (v38 == NULL) {
                                                                    // 0x804a239
                                                                    v4 = (char **)next_token3;
                                                                    int32_t ini_seg_bytes = strspn(next_token3, &accept2); // 0x804a24c
                                                                    if (ini_seg_bytes == -1 - -1 * strlen(next_token3)) {
                                                                        int32_t size9 = 1 - -1 * strlen(next_token3); // 0x804a2c2
                                                                        v4 = (char **)size9;
                                                                        char * mem10 = malloc(size9); // 0x804a2cd
                                                                        v4 = (char **)mem10;
                                                                        char * dest_str = strcpy(mem10, next_token3); // 0x804a2eb
                                                                        v4 = NULL;
                                                                        mysql_init();
                                                                        int32_t * v43 = dest_str == NULL ? (int32_t *)-1 : NULL; // bp+040
                                                                        mysql_real_connect();
                                                                        int32_t v44 = (int32_t)dest_str; // 0x804a368
                                                                        int32_t * v45 = v44 == 0 ? (int32_t *)-2 : v43; // bp+039
                                                                        v42 = v45;
                                                                        if (v45 == NULL) {
                                                                            // 0x804a38e
                                                                            mysql_autocommit();
                                                                            int32_t v46 = ProceedTransaction((char **)v44, mem2, (struct struct__IO_FILE *)mem3, (struct struct__IO_FILE *)v35, (char *)(int32_t)(float32_t)(float80_t)str_as_d, 0); // 0x804a3df
                                                                            if (v46 == 0) {
                                                                                // 0x804a3f3
                                                                                mysql_commit();
                                                                                // branch -> 0x804a411
                                                                            } else {
                                                                                // 0x804a403
                                                                                mysql_rollback();
                                                                                // branch -> 0x804a411
                                                                            }
                                                                            // 0x804a411
                                                                            mysql_autocommit();
                                                                            v42 = (int32_t *)v46;
                                                                            // branch -> 0x804a427
                                                                        }
                                                                        // 0x804a427
                                                                        mysql_close();
                                                                        v33 = (char **)mem10;
                                                                        // branch -> 0x804a435
                                                                      lab_0x804a435:
                                                                        // 0x804a435
                                                                        v4 = (char **)"%d \n";
                                                                        printf("%d \n", (int32_t)v42);
                                                                        if (v35 != NULL) {
                                                                            // 0x804a455
                                                                            v4 = v35;
                                                                            free((char *)v35);
                                                                            // branch -> 0x804a463
                                                                        }
                                                                        // 0x804a463
                                                                        if (v33 != NULL) {
                                                                            // break (via goto) -> 0x804a470
                                                                            goto lab_0x804a470;
                                                                        }
                                                                        // continue (via goto) -> 0x8049ea0
                                                                        goto lab_0x8049ea0_2;
                                                                    } else {
                                                                        v41 = (int32_t *)-38;
                                                                    }
                                                                }
                                                                // 0x804a2f0
                                                                v33 = NULL;
                                                                v42 = v41;
                                                                // branch -> 0x804a435
                                                                goto lab_0x804a435;
                                                            }
                                                        }
                                                        // 0x804a141
                                                        v37 = (int32_t *)-36;
                                                        // branch -> 0x804a14b
                                                        goto lab_0x804a14b;
                                                    }
                                                }
                                                // after_if_804a130_0.thread
                                                // branch -> 0x804a136
                                                goto lab_0x804a136;
                                            }
                                            // 0x804a14b
                                            v4 = NULL;
                                            next_token3 = strtok(NULL, ",");
                                            v39 = next_token3 == NULL ? (int32_t *)-31 : v37;
                                            if (v39 == NULL) {
                                                goto lab_0x804a182;
                                            }
                                            v38 = v39;
                                            goto lab_0x804a1fa;
                                        } else {
                                            // 0x8049e88
                                            v4 = (char **)"-15";
                                            printf("-15");
                                            // branch -> 0x804a48c
                                        }
                                        // 0x804a48c
                                        if (*(int32_t *)20 != v6) {
                                            // 0x804a498
                                            __stack_chk_fail();
                                            // branch -> 0x804a49d
                                        }
                                        // 0x804a49d
                                        return 0;
                                    }
                                  lab_0x8049db5:
                                    // 0x8049db5
                                    v31 = v17;
                                    v32 = v27;
                                    v22 = v11;
                                    // branch -> 0x8049db5
                                }
                              lab_0x804a470:
                                // 0x804a470
                                v4 = v33;
                                free((char *)v33);
                                // branch -> 0x8049ea0
                                goto lab_0x8049ea0;
                            } else {
                              lab_0x804945b:
                                // 0x804945b
                                v4 = (char **)mem8;
                                memcpy(mem8, mem7, size7);
                                v4 = (char **)mem7;
                                next_token4 = strtok(mem7, ",");
                                if (next_token4 != NULL) {
                                    // break -> 0x80494ac
                                    break;
                                }
                                // continue -> 0x80493bb
                                continue;
                            }
                        }
                        int32_t accept3 = 0x33323130;
                        char ** str4; // bp+055
                        int32_t * v47; // 0x05367
                        if (-((-1 * strlen(next_token4))) == 34) {
                            // 0x8049556
                            v4 = (char **)next_token4;
                            if (strspn(next_token4, (char *)&accept3) == 34) {
                                int32_t size10 = 1 - -1 * strlen(next_token4); // 0x80495b3
                                v4 = (char **)size10;
                                char * mem11 = malloc(size10); // 0x80495be
                                v4 = (char **)mem11;
                                strcpy(mem11, next_token4);
                                str4 = (char **)mem11;
                                v47 = NULL;
                                // branch -> 0x80495e1
                            } else {
                                str4 = NULL;
                                v47 = (int32_t *)-35;
                            }
                        } else {
                            // 0x80495e1
                            str4 = NULL;
                            v47 = (int32_t *)-34;
                            // branch -> 0x80495e1
                        }
                        // 0x80495e1
                        v4 = NULL;
                        char * next_token5 = strtok(NULL, ","); // 0x80495f1
                        int32_t * v48 = next_token5 == NULL ? (int32_t *)-31 : v47; // bp+052
                        *__errno_location() = 0;
                        float64_t v49 = 0.0; // 0x804965e35
                        if (next_token5 != NULL) {
                            // 0x804962b
                            v4 = (char **)next_token5;
                            strtod(next_token5, NULL);
                            v49 = v1;
                            // branch -> 0x8049647
                        }
                        int32_t * v50 = v48;
                        char ** str5; // bp+056
                        int32_t * v51; // 0x05170
                        if (v48 == NULL) {
                            float80_t v52 = v49; // 0x8049650
                            v1 = v52;
                            if (v49 >= 0.0) {
                                // if_8049658_0_false
                                if (v49 <= 0.0) {
                                    // if_8049658_1_false
                                    if (v49 != 0.0) {
                                      lab_0x804966c:
                                        // 0x804966c
                                        if (*__errno_location() == 0) {
                                            int32_t size11 = 1 - -1 * strlen(next_token5); // 0x80496b7
                                            v4 = (char **)size11;
                                            char * mem12 = malloc(size11); // 0x80496c2
                                            v4 = (char **)mem12;
                                            strcpy(mem12, next_token5);
                                            v51 = NULL;
                                            str5 = (char **)mem12;
                                            // branch -> 0x80496e5
                                          lab_0x80496e5_2:
                                            // 0x80496e5
                                            v4 = NULL;
                                            char * next_token6 = strtok(NULL, ","); // 0x80496f5
                                            int32_t * v53 = next_token6 == NULL ? (int32_t *)-31 : v51; // bp+050
                                            int32_t * v54 = v53; // bp+049
                                            if (v53 == NULL) {
                                                // 0x804971c
                                                if (-((-1 * strlen(next_token6))) >= 151) {
                                                    // 0x804974b
                                                    v54 = (int32_t *)-37;
                                                    // branch -> 0x8049794
                                                } else {
                                                    v54 = NULL;
                                                }
                                            }
                                            char accept4 = 48;
                                            int32_t v55;
                                            memcpy((char *)&v55, (char *)0x804a739, 16);
                                            *(int16_t *)&v55 = *(int16_t *)0x804a739;
                                            *(char *)((int32_t)&v55 | 2) = *(char *)0x804a73b;
                                            char ** v56; // 0x05779
                                            if (v54 == NULL) {
                                                // 0x80497d3
                                                v4 = (char **)next_token6;
                                                int32_t ini_seg_bytes2 = strspn(next_token6, &accept4); // 0x80497e6
                                                if (ini_seg_bytes2 == -1 - -1 * strlen(next_token6)) {
                                                    int32_t size12 = 1 - -1 * strlen(next_token6); // 0x804985c
                                                    v4 = (char **)size12;
                                                    char * mem13 = malloc(size12); // 0x8049867
                                                    v4 = (char **)mem13;
                                                    strcpy(mem13, next_token6);
                                                    int32_t len = strlen((char *)str4); // 0x80498c4
                                                    int32_t len2 = strlen((char *)str5); // 0x80498ec
                                                    int32_t len3 = strlen(mem4); // 0x8049916
                                                    int32_t v57 = 1 - -1 * strlen(mem5) + len2 + len + len3; // 0x804994b
                                                    uint32_t v58 = v57 + 30; // 0x804996e
                                                    uint32_t v59 = v58 % 16 - v58 + g1 + 47; // 0x804998e
                                                    char * str7 = (char *)(v59 - v59 % 16); // 0x80499b8_2
                                                    memset(str7, 0, v57);
                                                    accept = 0;
                                                    v19 = 0;
                                                    *(int32_t *)(v15 + 4) = 0;
                                                    int32_t v60 = 8; // 0x80499f3
                                                    int32_t v61 = v15;
                                                    int32_t v62 = 0;
                                                    // branch -> 0x80499f0
                                                    while (v60 < 24) {
                                                        // 0x80499f0
                                                        *(int32_t *)(v61 + v60) = v62;
                                                        v60 += 4;
                                                        v61 = v15;
                                                        v62 = 0;
                                                        // continue -> 0x80499f0
                                                    }
                                                    // 0x8049c53
                                                    *(int16_t *)(v61 + v60) = (int16_t)v62;
                                                    accept = 0;
                                                    int32_t v63;
                                                    memset((char *)&v63, 0, 7);
                                                    *(int16_t *)&v63 = 0;
                                                    *(char *)((int32_t)&v63 | 2) = 0;
                                                    int32_t len4 = strlen((char *)&str6); // 0x8049a81
                                                    int32_t len5 = strlen((char *)&accept); // 0x8049aa9
                                                    int32_t v64;
                                                    memset((char *)&v64, 0, 1 - -1 * len5 + len4);
                                                    strcat(str7, (char *)str4);
                                                    strcat(str7, (char *)str5);
                                                    strcat(str7, mem4);
                                                    strcat(str7, mem5);
                                                    strlen(str7);
                                                    SHA256();
                                                    v64 = str6;
                                                    accept2 = 0;
                                                    int32_t v65;
                                                    memset((char *)&v65, 0, 15);
                                                    int16_t str8 = 0;
                                                    // branch -> 0x8049c87
                                                    for (int32_t i = 0; i < 64; i++) {
                                                        unsigned char v66 = *(char *)(i + (int32_t)&v64); // 0x8049c93
                                                        sprintf((char *)&str8, "%02x", (int32_t)v66);
                                                        strcat(&accept2, (char *)&str8);
                                                        // continue -> 0x8049c87
                                                    }
                                                    // 0x8049cdc
                                                    strlen(&accept2);
                                                    SHA256();
                                                    g1 = v5;
                                                    v56 = (char **)mem13;
                                                    // branch -> 0x8049d1f
                                                  lab_0x8049d1f:
                                                    // 0x8049d1f
                                                    if (str4 != NULL) {
                                                        // 0x8049d28
                                                        v4 = str4;
                                                        free((char *)str4);
                                                        // branch -> 0x8049d36
                                                    }
                                                    // 0x8049d36
                                                    if (v56 != NULL) {
                                                        // 0x8049d3f
                                                        v4 = v56;
                                                        free((char *)v56);
                                                        // branch -> 0x8049d4d
                                                    }
                                                    // 0x8049d4d
                                                    if (str5 != NULL) {
                                                        // break (via goto) -> 0x8049d5a
                                                        goto lab_0x8049d5a;
                                                    }
                                                    // continue (via goto) -> 0x80493bb
                                                    goto lab_0x80493bb_2;
                                                }
                                            }
                                            // 0x804988a
                                            v56 = NULL;
                                            // branch -> 0x8049d1f
                                            goto lab_0x8049d1f;
                                        }
                                    } else {
                                        // after_if_8049666_0
                                        v1 = v52;
                                        // branch -> 0x8049681
                                    }
                                    // 0x8049681
                                    v51 = (int32_t *)-36;
                                    str5 = NULL;
                                    // branch -> 0x80496e5
                                    goto lab_0x80496e5_2;
                                }
                            }
                            // after_if_8049666_0.thread
                            v1 = v52;
                            // branch -> 0x804966c
                            goto lab_0x804966c;
                        }
                        // 0x8049681
                        v51 = v50;
                        str5 = NULL;
                        // branch -> 0x80496e5
                        goto lab_0x80496e5_2;
                    }
                    // 0x80493a7
                    v14 = &str6;
                    str6 = 0;
                    *(int32_t *)(v14 + 4) = 0;
                    v10 = 8;
                    v26 = v14;
                    v29 = 0;
                    // branch -> 0x80493a7
                    while (v10 < 20) {
                        // 0x80493a7
                        *(int32_t *)(v26 + v10) = v29;
                        v10 += 4;
                        v26 = v14;
                        v29 = 0;
                        // continue -> 0x80493a7
                    }
                    // 0x80493b1
                    *(char *)(v10 + v26) = (char)v29;
                    v15 = &v19;
                    // branch -> 0x80493bb
                  lab_0x80493bb_2:
                    while (true) {
                        // 0x80493bb
                        v4 = (char **)mem7;
                        memset(mem7, 0, size7);
                        v4 = (char **)mem8;
                        memset(mem8, 0, size7);
                        v4 = (char **)mem7;
                        fgets(mem7, curr_file_offset, file);
                        v4 = (char **)mem7;
                        if (memcmp(mem7, mem8, curr_file_offset) != 0) {
                            goto lab_0x804945b;
                        }
                        // 0x8049dab
                        str3 = 0;
                        v17 = 0;
                        v16 = &v20;
                        v18 = 28;
                        v22 = 0;
                        // branch -> 0x8049db5
                        while (true) {
                            // 0x8049db5
                            *(int32_t *)(v22 + v16) = 0;
                            v11 = v22 + 4;
                            v27 = v16;
                            if (v11 < 28) {
                                goto lab_0x8049db5;
                            }
                            // 0x8049dbf
                            v13 = v27 + v11;
                            v23 = v18;
                            v24 = v13;
                            v28 = v23;
                            if ((v23 & 2) != 0) {
                                // 0x8049dca
                                *(int16_t *)v13 = (int16_t)v17;
                                v24 = v13 + 2;
                                v28 = v18;
                                // branch -> 0x8049dd0
                            }
                            // 0x8049dd0
                            if (v28 % 2 != 0) {
                                // 0x8049dd7
                                *(char *)v24 = (char)v17;
                                // branch -> 0x8049ddc
                            }
                            // 0x8049ddc
                            str2 = 0;
                            v21 = 0;
                            v25 = *(char *)(v21 + v14);
                            sprintf((char *)&str2, "%02x", (int32_t)v25);
                            strcat((char *)&str3, (char *)&str2);
                            v12 = v21 + 1;
                            // branch -> 0x8049e02
                            while (v12 < 32) {
                                // 0x8049e02
                                v21 = v12;
                                v25 = *(char *)(v21 + v14);
                                sprintf((char *)&str2, "%02x", (int32_t)v25);
                                strcat((char *)&str3, (char *)&str2);
                                v12 = v21 + 1;
                                // continue -> 0x8049e02
                            }
                            // 0x8049e51
                            v4 = (char **)file;
                            fseek(file, 0, SEEK_SET);
                            if (strcmp((char *)&str3, mem6) == 0) {
                                // 0x8049ea0
                                // branch -> 0x8049ea0
                              lab_0x8049ea0_2:
                                while (true) {
                                    // 0x8049ea0
                                    v4 = (char **)mem7;
                                    memset(mem7, 0, size7);
                                    v4 = (char **)mem8;
                                    memset(mem8, 0, size7);
                                    v4 = (char **)mem7;
                                    fgets(mem7, curr_file_offset, file);
                                    v4 = (char **)mem7;
                                    if (memcmp(mem7, mem8, curr_file_offset) != 0) {
                                        goto lab_0x8049f40;
                                    }
                                    // 0x804a48c
                                    if (*(int32_t *)20 != v6) {
                                        // 0x804a498
                                        __stack_chk_fail();
                                        // branch -> 0x804a49d
                                    }
                                    // 0x804a49d
                                    return 0;
                                }
                            } else {
                                // 0x8049e88
                                v4 = (char **)"-15";
                                printf("-15");
                                // branch -> 0x804a48c
                            }
                            // 0x804a48c
                            if (*(int32_t *)20 != v6) {
                                // 0x804a498
                                __stack_chk_fail();
                                // branch -> 0x804a49d
                            }
                            // 0x804a49d
                            return 0;
                        }
                    }
                } else {
                    result = -1;
                }
            } else {
                result = -1;
            }
        }
        // 0x804a48c
        if (*(int32_t *)20 != v6) {
            // 0x804a498
            __stack_chk_fail();
            // branch -> 0x804a49d
        }
        // 0x804a49d
        return result;
    }
    // 0x804a48c
    if (*(int32_t *)20 != v6) {
        // 0x804a498
        __stack_chk_fail();
        // branch -> 0x804a49d
    }
    // 0x804a49d
    return 1;
}

// --------------- Dynamically Linked Functions ---------------

// int * __errno_location(void);
// void __stack_chk_fail(void);
// char * fgets(char *restrict, int, FILE *restrict);
// FILE * fopen(const char *restrict, const char *restrict);
// void free(void *);
// int fseek(FILE *, long, int);
// long ftell(FILE *);
// void * malloc(size_t);
// int memcmp(const void *, const void *, size_t);
// void * memcpy(void *restrict, const void *restrict, size_t);
// void * memset(void *, int, size_t);
// void mysql_autocommit(void);
// void mysql_close(void);
// void mysql_commit(void);
// void mysql_fetch_row(void);
// void mysql_init(void);
// void mysql_real_connect(void);
// void mysql_real_query(void);
// void mysql_rollback(void);
// void mysql_store_result(void);
// void perror(const char *);
// int printf(const char *restrict, ...);
// void SHA256(void);
// int sprintf(char *restrict, const char *restrict, ...);
// char * strcat(char *restrict, const char *restrict);
// int strcmp(const char *, const char *);
// char * strcpy(char *restrict, const char *restrict);
// size_t strspn(const char *, const char *);
// double strtod(const char *restrict, char **restrict);
// char * strtok(char *restrict, const char *restrict);

// --------------- Instruction-Idiom Functions ----------------

// int32_t strlen(char * a1);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.6.3)
// Detected functions: 2
// Decompiler release: v2.1.1.1 (2015-11-18)
// Decompilation date: 2016-01-02 10:00:36
